name: Generate Fixed Debug Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storetype JKS -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"

      - name: Print SHA-1
        run: keytool -list -v -keystore debug.keystore -alias androiddebugkey -storepass android -keypass android

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: fixed-debug-keystore
          path: debug.keystore
